language: python
python:
  - "3.6"
  - "3.7"


# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade  -r requirements.txt
  - pip install coverage codecov
  - pip install .

# command to run tests
script:
  - coverage run -p examples/example1.py


# Push the results back to codecov
after_success:
  - coverage combine
  - codecov